# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Have You Tried Turning It Off And On Again ?
tagline:          'Keep Calm And Call A DBA'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://emerichunter.github.io
baseurl:          /

author:
  name:           'EmericHunter'
  url:            http://www.loxodata.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/emerichunter
